baseURL = 'https://denniscmartin.com/'
languageCode = 'en-us'
title = 'Dennis C. Martín'
theme = 'mytheme'
copyright = '© 2024 Dennis Concepción Martín'
[params]
    thumbnail = 'thumbnail'
    [params.author]
        name = 'Dennis Concepción Martín'
        email = 'dennis@denniscmartin.com'
        twitter = '@dennisconcep'

