baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My journal'
copyright = '© [Year] All rights reserved.'
[params]
    cdnBaseUrl = 'https://media.example.org'
    thumbnail = 'thumbnail.png'
    [params.author]
        name = 'Dennis Concepción Martín'
        email = 'dennis@denniscmartin.com'
        twitter = '@dennisconcep'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Notes'
pageRef = '/notes'
weight = 30

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 40

[[menus.footer]]
name = 'Tags'
pageRef = '/tags'
weight = 10

[[menus.footer]]
name = 'RSS'
url = '/index.xml'
weight = 20

[[menus.footer]]
name = 'Sitemap'
url = '/sitemap.xml'
weight = 30

[[menus.footer]]
name = 'License'
pageRef = '/license'
weight = 40

[[menus.footer]]
name = 'Privacy'
pageRef = '/privacy'
weight = 50

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
