name = 'Custom theme'
license = 'MIT'
licenselink = 'https://github.com/denniscmartin/denniscmartin.com/themes/my-theme/LICENSE'
homepage = 'https://github.com/denniscmartin/denniscmartin.com/themes/my-theme'
